spring.application.name=resort-service
server.port=8082

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=resortdb;encrypt=false
spring.datasource.username=resort_admin
spring.datasource.password=ResortAdmin@123

# spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# NO SECURITY CONFIG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.web: DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.hibernate.SQL: DEBUG

# jwt.secret=HuwSnDiVZJYzhoQ7fIBLBc3CuIzzwY3VY6mvAxfKX2ZoJYJ0+iqxnfKW1NjNAnPKwHsCC/gLAOxRZt5bsySQtA==  # Base64 encoded secret (e.g., "secret123" => "c2VjcmV0MTIz")
# spring.security.oauth2.resourceserver.jwt.secret-key=HuwSnDiVZJYzhoQ7fIBLBc3CuIzzwY3VY6mvAxfKX2ZoJYJ0+iqxnfKW1NjNAnPKwHsCC/gLAOxRZt5bsySQtA==
# jwt.expirationMs=86400000  # 24 hours in milliseconds


